spring:
  config:
    activate:
      on-profile: ex1
  datasource:
    url: jdbc:h2:mem:produtos
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    root: INFO