
services:
  postgres:
    image: postgres:15
    container_name: postgres_eventos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: eventos_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres_escola:
    image: postgres:15
    container_name: postgres_escola
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: escola_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_escola_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_escola_data:
