spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:55432/teachgram}
    username: ${DATABASE_USERNAME:teachgram}
    password: ${DATABASE_PASSWORD:teachgram}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  data:
    redis:
      url: ${REDIS_URL:}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

logging:
  level:
    dev.charlles.teachgram: DEBUG
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
