# Exercício 1 - Produtos In-Memory
FROM eclipse-temurin:25-jre AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Dspring.profiles.active=ex1", "-jar", "app.jar", "--main-class=com.teach3035.exercicio1_produtos_inmemory.Application"]