services:
  postgres:
    image: postgres:16-alpine
    container_name: teachgram-postgres
    environment:
      POSTGRES_DB: teachgram
      POSTGRES_USER: teachgram
      POSTGRES_PASSWORD: teachgram
    ports:
      - "${POSTGRES_PORT:-55432}:5432"
    volumes:
      - teachgram-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teachgram -d teachgram"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: teachgram-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: teachgram-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: teachgram
      RABBITMQ_DEFAULT_PASS: teachgram

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: teachgram-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    env_file:
      - ../.env
    environment:
      - GRAFANA_CLOUD_USER=${GRAFANA_CLOUD_USER}
      - GRAFANA_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=expand-external-variables'

#  grafana:
#    image: grafana/grafana:11.3.1
#    container_name: teachgram-grafana
#    ports:
#      - "3000:3000"
#    environment:
#      GF_SECURITY_ADMIN_USER: admin
#      GF_SECURITY_ADMIN_PASSWORD: admin
#      GF_AUTH_ANONYMOUS_ENABLED: "true"
#      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
#    volumes:
#      - teachgram-grafana-data:/var/lib/grafana

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: teachgram-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres.irkuvpvxxvfakcnwbqka:raCDrzgWEvfAoFvb@aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require"

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: teachgram-redis-exporter
    environment:
      REDIS_ADDR: "rediss://deep-goshawk-123695.upstash.io:6379"
      REDIS_PASSWORD: "gQAAAAAAAeMvAAIgcDExZTY3MGY3MTFlM2Y0NjQwYWEzMjVmMjkxNDcyZTU0Yw"

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: teachgram-blackbox-exporter
    ports:
      - "9115:9115"

volumes:
  teachgram-postgres-data:
  teachgram-grafana-data:
